### ISSUE TITLE
Use core.hooksPath instead of git-hooks

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-git#37]
git 2.9 introduced a core.hooksPath property that points to a directory of hooks that will run for all repositories (when set in the global git configuration). We should use this instead of git-hooks. Maybe raise a warning to people running older gits to let them know they should upgrade?

/cc @aramprice

**Comment by aramprice** [comment]
This addresses part of the problem which the `git-hooks` integration addresses which is "how to I ensure that all repos have my hooks applied". The current mechanism for this is two-fold:
1. install `git-hooks` into every existing repo
2. modify `init.templateDir` to point to a template directory which has `git-hooks` installed (into `{init.templateDir}/hooks/`)

The other problem `git-hooks` seeks to address is "run multiple hooks for each hook-event from multiple sources". The new `core.hooksPath` setting doesn't help with this at all because git still expects to find and run exactly one hook per event (`{core.hooksPath}/hooks/{event-name}`).

**Comment by aramprice** [comment]
Note: this require git `>= 2.9`

**Comment by aramprice** [comment]
Closing, see: 
- https://github.com/pivotal-sprout/sprout-git/pull/42
- https://github.com/pivotal-sprout/sprout-git/pull/43
